### ISSUE TITLE
Add CICD

### ISSUE THREAD

**Issue by lucacucchetti** [lucacucchetti/duck-awareness#3]
Deploy to our "prod" should be done only by a pipeline when merging to `main` branch.

We can setup CodePipeline and stuff in AWS but it will probably cost money, investigate first if it is free in Github.

**Comment by mikhasd** [comment]
@lucacucchetti, Can CDK output the required IAM permissions required to execute the stack?
If so, we should create a deployment user to be used on the CICD pipeline.

**Comment by lucacucchetti** [comment]
@mikhasd CDK can create IAM resources but instead of a User maybe we should use a Role? From a quick search it looks like GitHub Actions supports federation? https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html

**Comment by mikhasd** [comment]
Ok. I'll limit the scope of this issue to creating a simple pipeline that run tests and deploy the stack from the master branch.

We can create a more elaborated CICD pipeline with time.

**Comment by mikhasd** [comment]
@lucacucchetti should we move the typescript compiler output to ./dist?
I'm having problems when running builds locally and having many .js and .d.ts files across the workspace.

**Comment by lucacucchetti** [comment]
Yes that's a good point, feel free to make an Issue or just do it, otherwise I can eventually get to it.
